### PR TITLE
2nd attempt at fixing pom for jenkins

### PR DESCRIPTION
**Pull request by gipsy-king**

### CODE REVIEW

**Comment by rourke750** [comment]
Copies [these](https://github.com/Civcraft/NameLayerNMS/blob/master/pom.xml#L64)

**Comment by ttk2** [comment]
so this this good now?

**Comment by gipsy-king** [comment]
it can only be tested by building with civcraft jenkins

**Comment by ttk2** [comment]
roruke said somthing else needed to be done.

**Comment by gipsy-king** [comment]
it has now all spigot deps like in NL-NMS I believe

**Comment by ttk2** [comment]
well lets try

**Comment by ttk2** [comment]
well it compiles, now, it does not work though 

2015-07-11 12:17:24 [INFO] [Burricos] Enabling Burricos v1.7
2015-07-11 12:17:24 [WARN] java.lang.ClassNotFoundException: com.gipsyking.Burricos.misc.v1_8_R3.NMSWrapper
2015-07-11 12:17:24 [WARN]      at java.net.URLClassLoader.findClass(URLClassLoader.java:381)
2015-07-11 12:17:24 [WARN]      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:101)
2015-07-11 12:17:24 [WARN]      at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:86)
2015-07-11 12:17:24 [WARN]      at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
2015-07-11 12:17:24 [WARN]      at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
2015-07-11 12:17:24 [WARN]      at java.lang.Class.forName0(Native Method)
2015-07-11 12:17:24 [WARN]      at java.lang.Class.forName(Class.java:264)
2015-07-11 12:17:24 [WARN]      at com.gipsyking.Burricos.misc.ClassHandler.Initialize(ClassHandler.java:21)
2015-07-11 12:17:24 [WARN]      at com.gipsyking.Burricos.Burricos.onEnable(Burricos.java:52)
2015-07-11 12:17:24 [WARN]      at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321)
2015-07-11 12:17:24 [WARN]      at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:340)
2015-07-11 12:17:24 [WARN]      at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:405)
2015-07-11 12:17:24 [WARN]      at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:356)
2015-07-11 12:17:24 [WARN]      at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:316)
2015-07-11 12:17:24 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:418)
2015-07-11 12:17:24 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:382)
2015-07-11 12:17:24 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:337)
2015-07-11 12:17:24 [WARN]      at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:256)
2015-07-11 12:17:24 [WARN]      at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:528)
2015-07-11 12:17:24 [WARN]      at java.lang.Thread.run(Thread.java:745)
2015-07-11 12:17:24 [ERROR] [Burricos] Cannot load NBT wrapper for server version: v1_8_R3

**Pull request merged**
