### PR TITLE
update to 1.8.7, bump version to 1.7

### PR DESCRIPTION
**Pull request by gipsy-king**

### CODE REVIEW

**Comment by rourke750** [comment]
ok to test

**Comment by rourke750** [comment]
@ttk2

**Comment by ttk2** [comment]
nice to Civtest it goes.

**Comment by ttk2** [comment]
um build failed.

**Comment by rourke750** [comment]
@gipsy-king can you look at NameLayer nms pom for building against out spigot builts.

@ttk2 if he doesn't get the chance to I'll do it as soon as I get the chance.

**Comment by gipsy-king** [comment]
Yes will do, sorry for breaking it

**Pull request merged**
