### PR TITLE
1.8.3

### PR DESCRIPTION
**Pull request by gipsy-king**
tested with 1.8.3, seems to work as expected

### CODE REVIEW

**Comment by rourke750** [comment]
Can you modify the pom and include these three dependencies: https://github.com/Civcraft/NameLayer/blob/master/pom.xml#L38
https://github.com/Civcraft/NameLayer/blob/master/pom.xml#L32
https://github.com/Civcraft/NameLayer/blob/master/pom.xml#L44

Its just for jenkins so it builds properly.

**Comment by rourke750** [comment]
Thx for the help

**Comment by gipsy-king** [comment]
Changed, although for some reasons it doesn't build on my machine anymore - it should work, as I have built other plugins depending on spigot 1.8.

**Comment by rourke750** [comment]
@gipsy-king Wait how did you getting it to build against one version of spigot since it would need to reference both 1.7.10, 1.8.1, and 1.8.3?

**Comment by gipsy-king** [comment]
@rourke750 sorry, I have no idea. In eclipse, the packages that reference nms stuff that are not for the craftbukkit version of the pom are marked as erroneous, but `mvn install` still builds the .jar

**Comment by rourke750** [comment]
@gipsy-king Huh, well anyways the reason why it won't build is because I kind of had to upload a 1.8.3 version of spigot to the jenkins server and give it a new artifact name.  Maven doesn't allow different versions to count at different dependencies because they believe that you shouldn't do that.  So I have to change it.  Although for local testing in eclipse you can always export the jar as long as you have the references.  Need to find a cleaner way to do this.

**Comment by gipsy-king** [comment]
@rourke750 I'm lost with maven, sorry :(

**Comment by rourke750** [comment]
@gipsy-king What do you mean?  Oh also for your local testing zone set up your maven how you had it before if you like.  Jenkins just needs to be configured this way for it to build.

**Comment by gipsy-king** [comment]
@rourke750 I mean I don't know anything about it, I don't do java at my job. And yea I will just change the pom to get a built when I need it. I only have to build when I update something, which should be never :)

**Pull request merged**
